# Generated by Django 3.0.4 on 2020-03-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myevents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('exercise', 'Exercise'), ('wellness', 'Wellness'), ('science', 'Science'), ('news', 'News'), ('chillin', 'Chillin'), ('other', 'Other')], default='other', max_length=128),
        ),
    ]
