# Generated by Django 3.0.4 on 2020-04-02 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myevents', '0002_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('exercise', 'Exercise'), ('wellness', 'Wellness'), ('science', 'Science'), ('news', 'News'), ('chillin', 'Chillin'), ('music', 'Music'), ('education', 'Education'), ('other', 'Other')], default='other', max_length=128),
        ),
    ]
